FROM alpine:3.22

RUN apk update && apk add --no-cache \
    mariadb \
    mariadb-client

COPY tools/db-setup.sh /usr/local/bin/db-setup.sh

RUN chmod +x /usr/local/bin/db-setup.sh

EXPOSE 3306

ENTRYPOINT ["/usr/local/bin/db-setup.sh"]