FROM alpine:3.18

RUN apk update && apk add --no-cache \
    mariadb \
    mariadb-client

RUN mkdir -p /var/lib/mysql \
    && chown -R mysql:mysql /var/lib/mysql

RUN mkdir -p /run/mysqld \
    && chown -R mysql:mysql /run/mysqld

COPY conf/my.cnf /etc/my.cnf.d/inception.cnf

COPY tools/db-setup.sh /usr/local/bin/db-setup.sh
RUN chmod +x /usr/local/bin/db-setup.sh

EXPOSE 3306

ENTRYPOINT ["/usr/local/bin/db-setup.sh"]