FROM alpine:3.18

RUN apk update && apk add --no-cache \
    nginx \
    openssl

# Create the directory for SSL certs
RUN mkdir -p /etc/nginx/ssl

# Generate a self-signed TLS certificate (valid 365 days, RSA 2048)
RUN openssl req -x509 -nodes -days 365 \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/C=MA/L=KH/O=1337/OU=student/CN=ayel-arr.42.fr"

COPY conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 443

# Start nginx in the foreground (NOT as a daemon — PID 1 rule)
CMD ["nginx", "-g", "daemon off;"]
